version: 2

project_name: private-llm

builds:
  - id: cli
    dir: ./cli
    binary: private-llm
    ldflags:
      - -s -w -X main.version={{.Version}}
    targets:
      - darwin_arm64
      - darwin_amd64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - formats:
      - tar.gz
    format_overrides:
      - goos: windows
        formats:
          - zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: stewartpark
    name: private-llm

source:
  enabled: true

changelog:
  sort: asc

nfpms:
  - id: linux_packages
    package_name: private-llm
    vendor: Stewart Park
    homepage: https://github.com/stewartpark/private-llm
    maintainer: Stewart Park <stewart@private-llm>
    description: Private LLM Agent Proxy with mTLS and auto-scaling GPU VM
    license: MIT
    dependencies:
      - systemd
    ids:
      - cli
    contents:
      - src: ./packaging/linux/systemd/private-llm.service
        dst: /usr/lib/systemd/system/private-llm.service
      - dst: /var/lib/private-llm
        type: dir
        file_info:
          mode: 0755
      - dst: /etc/private-llm
        type: dir
        file_info:
          mode: 0755
    scripts:
      postinstall: ./packaging/linux/deb/postinst
      postremove: ./packaging/linux/deb/postrm
    formats:
      - deb
      - rpm
