version: 2

project_name: private-llm

builds:
  - dir: ./cli
    binary: private-llm
    ldflags:
      - -s -w -X main.version={{.Version}}
    targets:
      - darwin_arm64
      - darwin_amd64
      - linux_amd64
      - linux_arm64
      - windows_amd64

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: checksums.txt
  algorithm: sha256

release:
  github:
    owner: stewartpark
    name: private-llm

source:
  enabled: true

changelog:
  sort: asc
