/* Sparkle umbrella header */
#import <Sparkle/SPUDownloadData.h>
#import <Sparkle/SPUUpdaterDelegate.h>
#import <Sparkle/SUVersionDisplayProtocol.h>
#import <Sparkle/SUAppcast.h>
#import <Sparkle/SPUUpdaterSettings.h>
#import <Sparkle/SPUAppcastSigningValidationStatus.h>
#import <Sparkle/SUExport.h>
#import <Sparkle/SPUStandardUserDriver.h>
#import <Sparkle/SPUUserUpdateState.h>
#import <Sparkle/SUUpdaterDelegate.h>
#import <Sparkle/SPUUserDriver.h>
#import <Sparkle/SUErrors.h>
#import <Sparkle/SUAppcastItem.h>
#import <Sparkle/SPUStandardUserDriverDelegate.h>
#import <Sparkle/SUStandardVersionComparator.h>
#import <Sparkle/SPUUpdateCheck.h>
#import <Sparkle/SPUUpdater.h>
#import <Sparkle/SUUpdater.h>
#import <Sparkle/SPUStandardUpdaterController.h>
#import <Sparkle/SPUUpdatePermissionRequest.h>
#import <Sparkle/SUVersionComparisonProtocol.h>
#import <Sparkle/SUUpdatePermissionResponse.h>
